In [2]:
# Import your libraries
import pandas as pd
import matplotlib.pyplot as plt

# Initialize variables for channels and videos 
channels = pd.read_excel("youtube_tech_channels_20251120_133753.xlsx")
videos = pd.read_excel("youtube_tech_videos_20251120_133004.xlsx")

print("Channels:", channels.shape)
print("Videos:", videos.shape)
channels.head()

Channels: (130, 10)
Videos: (1300, 13)

,channel_id,channel_name,description,subscribers,total_views,total_videos,created_date,country,uploads_playlist,scraped_at
0,UCXuqSBlHAE6Xw-yeJA0Tunw,Linus Tech Tips,"Linus Tech Tips is a passionate team of ""profe...",16600000,9092244390,6989,2008-11-25T00:46:52Z,CA,UUXuqSBlHAE6Xw-yeJA0Tunw,2025-11-20T13:37:53.306286
1,UCWv7vMbMWH4-V0ZXdmDpPBA,Programming with Mosh,"Hi! I'm Mosh ðŸ‘‹, a software engineer with ov...",4860000,257598451,243,2014-10-07T00:40:53Z,US,UUWv7vMbMWH4-V0ZXdmDpPBA,2025-11-20T13:37:53.306286
2,UChIZGfcnjHI0DG4nweWEduw,TechSource,Join the Discord Server:\nhttps://discord.gg/T...,4010000,870967915,1897,2010-01-24T22:34:11Z,US,UUhIZGfcnjHI0DG4nweWEduw,2025-11-20T13:37:53.306286
3,UC4SVo0Ue36XCfOyb5Lh1viQ,Bro Code,Coding bootcamps HATE HIM! ðŸ—¿\n,2990000,178609297,1000,2019-10-10T14:40:46.568078Z,US,UU4SVo0Ue36XCfOyb5Lh1viQ,2025-11-20T13:37:53.306286
4,UCVeW9qkBjo3zosnqUbG7CFw,John Hammond,Free Cybersecurity Education and Ethical Hacking.,2080000,82120292,1740,2011-02-06T03:59:46Z,US,UUVeW9qkBjo3zosnqUbG7CFw,2025-11-20T13:37:53.306286

In [3]:
print(videos.columns.tolist())
print()
videos.info()
videos.head()

['video_id', 'title', 'published_at', 'views', 'likes', 'comments', 'duration', 'thumbnail', 'video_url', 'channel_id', 'channel_name', 'scraped_at', 'duration_readable']

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   video_id           1289 non-null   object
 1   title              1300 non-null   object
 2   published_at       1300 non-null   object
 3   views              1300 non-null   int64
 4   likes              1300 non-null   int64
 5   comments           1300 non-null   int64
 6   duration           1300 non-null   object
 7   thumbnail          1300 non-null   object
 8   video_url          1300 non-null   object
 9   channel_id         1300 non-null   object
 10  channel_name       1300 non-null   object
 11  scraped_at         1300 non-null   object
 12  duration_readable  1300 non-null   object
dtypes: int64(3), object(10)
memory usage: 132.2+ KB

,video_id,title,published_at,views,likes,comments,duration,thumbnail,video_url,channel_id,channel_name,scraped_at,duration_readable
0,zzlS5dtzKKA,Most Important LTTStore Step,2025-11-18T22:47:05Z,211782,4012,88,PT27S,https://i.ytimg.com/vi/zzlS5dtzKKA/hqdefault.jpg,https://www.youtube.com/watch?v=zzlS5dtzKKA,UCXuqSBlHAE6Xw-yeJA0Tunw,Linus Tech Tips,2025-11-20T13:37:53.306773,00:27:00
1,Cmnfwabz0bA,This TV Factory is the Coolest Iâ€™ve Ever Seen,2025-11-18T19:20:33Z,572162,29769,1876,PT13M43S,https://i.ytimg.com/vi/Cmnfwabz0bA/hqdefault.jpg,https://www.youtube.com/watch?v=Cmnfwabz0bA,UCXuqSBlHAE6Xw-yeJA0Tunw,Linus Tech Tips,2025-11-20T13:37:53.306773,13:43:00
2,dnKy4UEdiyo,The Hardest Secrets Iâ€™ve Ever Kept - WAN Sho...,2025-11-15T06:24:56Z,523009,10052,1798,PT4H30M52S,https://i.ytimg.com/vi/dnKy4UEdiyo/hqdefault.jpg,https://www.youtube.com/watch?v=dnKy4UEdiyo,UCXuqSBlHAE6Xw-yeJA0Tunw,Linus Tech Tips,2025-11-20T13:37:53.306773,04:30:52
3,WP3LKBHL8vQ,Correct Way to Apply Thermal Paste,2025-11-14T18:27:41Z,3002514,63873,514,PT34S,https://i.ytimg.com/vi/WP3LKBHL8vQ/hqdefault.jpg,https://www.youtube.com/watch?v=WP3LKBHL8vQ,UCXuqSBlHAE6Xw-yeJA0Tunw,Linus Tech Tips,2025-11-20T13:37:53.306773,00:34:00
4,g3FkuZNSGkw,Valveâ€™s New Console and Controller - STEAM M...,2025-11-13T13:54:48Z,4399002,161897,11391,PT14M31S,https://i.ytimg.com/vi/g3FkuZNSGkw/hqdefault.jpg,https://www.youtube.com/watch?v=g3FkuZNSGkw,UCXuqSBlHAE6Xw-yeJA0Tunw,Linus Tech Tips,2025-11-20T13:37:53.306773,14:31:00

In [4]:
channels.info()
print()
print("Missing values:")
print(channels.isna().sum())
print()
print("Duplicate channel IDs:", channels["channel_id"].duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   channel_id        130 non-null    object
 1   channel_name      130 non-null    object
 2   description       127 non-null    object
 3   subscribers       130 non-null    int64
 4   total_views       130 non-null    int64
 5   total_videos      130 non-null    int64
 6   created_date      130 non-null    object
 7   country           116 non-null    object
 8   uploads_playlist  130 non-null    object
 9   scraped_at        130 non-null    object
dtypes: int64(3), object(7)
memory usage: 10.3+ KB

Missing values:
channel_id           0
channel_name         0
description          3
subscribers          0
total_views          0
total_videos         0
created_date         0
country             14
uploads_playlist     0
scraped_at           0
dtype: int64

Duplicate channel IDs: 0

In [5]:
videos["published_at"] = pd.to_datetime(videos["published_at"])
videos["duration_min"] = pd.to_timedelta(videos["duration"]).dt.total_seconds() / 60

print(videos[["duration", "duration_readable", "duration_min"]].head())
print()
print(videos["duration_min"].describe())

     duration duration_readable  duration_min
0       PT27S          00:27:00      0.450000
1    PT13M43S          13:43:00     13.716667
2  PT4H30M52S          04:30:52    270.866667
3       PT34S          00:34:00      0.566667
4    PT14M31S          14:31:00     14.516667

count    1300.000000
mean       29.971936
std        71.095554
min         0.000000
25%         3.320833
50%        10.675000
75%        26.920833
max      1335.950000
Name: duration_min, dtype: float64

In [6]:
channels["created_date"] = pd.to_datetime(channels["created_date"], format="ISO8601", utc=True)
channels["scraped_at"] = pd.to_datetime(channels["scraped_at"], format="ISO8601", utc=True)
channels["age_years"] = (channels["scraped_at"] - channels["created_date"]).dt.days / 365.25

print(channels[["channel_name", "created_date", "age_years"]].head())
print()
print(channels["age_years"].describe())

            channel_name                     created_date  age_years
0        Linus Tech Tips        2008-11-25 00:46:52+00:00  16.985626
1  Programming with Mosh        2014-10-07 00:40:53+00:00  11.121150
2             TechSource        2010-01-24 22:34:11+00:00  15.819302
3               Bro Code 2019-10-10 14:40:46.568078+00:00   6.110883
4           John Hammond        2011-02-06 03:59:46+00:00  14.787132

count    130.000000
mean       8.910314
std        4.523787
min        0.741958
25%        5.539357
50%        8.242300
75%       11.930185
max       20.101300
Name: age_years, dtype: float64

In [7]:
videos["published_at"] = pd.to_datetime(videos["published_at"], format="ISO8601", utc=True)
videos["duration_min"] = pd.to_timedelta(videos["duration"]).dt.total_seconds() / 60

print(videos[["duration", "duration_readable", "duration_min"]].head())
print()
print(videos["duration_min"].describe())

     duration duration_readable  duration_min
0       PT27S          00:27:00      0.450000
1    PT13M43S          13:43:00     13.716667
2  PT4H30M52S          04:30:52    270.866667
3       PT34S          00:34:00      0.566667
4    PT14M31S          14:31:00     14.516667

count    1300.000000
mean       29.971936
std        71.095554
min         0.000000
25%         3.320833
50%        10.675000
75%        26.920833
max      1335.950000
Name: duration_min, dtype: float64

In [8]:
videos.info()
print()
print("Missing values:")
print(videos.isna().sum())
print()
print("Duplicate video IDs:", videos["video_id"].duplicated().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1300 entries, 0 to 1299
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   video_id           1289 non-null   object
 1   title              1300 non-null   object
 2   published_at       1300 non-null   datetime64[ns, UTC]
 3   views              1300 non-null   int64
 4   likes              1300 non-null   int64
 5   comments           1300 non-null   int64
 6   duration           1300 non-null   object
 7   thumbnail          1300 non-null   object
 8   video_url          1300 non-null   object
 9   channel_id         1300 non-null   object
 10  channel_name       1300 non-null   object
 11  scraped_at         1300 non-null   object
 12  duration_readable  1300 non-null   object
 13  duration_min       1300 non-null   float64
dtypes: datetime64[ns, UTC](1), float64(1), int64(3), object(9)
memory usage: 142.3+ KB

Missing values:
video_id             11
title                 0
published_at          0
views                 0
likes                 0
comments              0
duration              0
thumbnail             0
video_url             0
channel_id            0
channel_name          0
scraped_at            0
duration_readable     0
duration_min          0
dtype: int64

Duplicate video IDs: 10

In [9]:
# Rows with missing video_id
print("Missing video_id rows:")
print(videos[videos["video_id"].isna()][["title", "channel_name", "video_url", "views"]])
print()

# Duplicated video_ids (excluding blanks)
dupes = videos[videos["video_id"].notna() & videos["video_id"].duplicated(keep=False)]
print("Duplicated video_id rows:", len(dupes))
print(dupes.sort_values("video_id")[["video_id", "title", "channel_name", "views"]])
print()

# The zero-length videos
print("Zero-length videos:")
print(videos[videos["duration_min"] == 0][["title", "channel_name", "duration", "views"]])

Missing video_id rows:
                                                  title  \
92                       App Performance #SpotlightWeek
220   All Eyes on Nvidia Ahead of Earnings | Bloombe...
240   Khadas Mind 2 Mini PC + RTX 4060 Ti Dock = Por...
334   Cisco on Cisco:  How Cisco Unlocks the Power o...
424   Learn to Vibe Code in 10 Minutes (Full Beginne...
508                  Practical Typescript 9 - Tasks App
627                           Android pertama kamu apa?
857   Mini-Projeto 10 - FunÃ§Ã£o Principal - Tab 1 P...
881           Code review and Optimisation with ChatGPT
898   What Is Control Unit ? | Control Unit Function...
1191  Python Data Analysis: Data Analysis Examples i...

                channel_name                                    video_url  \
92        Android Developers  https://www.youtube.com/watch?v=-ReTLNec0VI
220     Bloomberg Technology  https://www.youtube.com/watch?v=-t58jx9r55U
240       Chigz Tech Reviews  https://www.youtube.com/watch?v=--SvQEZm20Y
334                    Cisco  https://www.youtube.com/watch?v=-pwB4klD67M
424           Tech With Lucy  https://www.youtube.com/watch?v=-LFB8D9WV-g
508            Coding Addict  https://www.youtube.com/watch?v=-qpUW_PVlIY
627              techandtips  https://www.youtube.com/watch?v=-nWumC2LG-I
857     Data Science Academy  https://www.youtube.com/watch?v=-tBJ4FtqG8M
881     Software Engineering  https://www.youtube.com/watch?v=-YKg7zOTbFQ
898   Learn Computer Science  https://www.youtube.com/watch?v=-Qs5Ypwnb9c
1191         Learning Python  https://www.youtube.com/watch?v=-GDo5hytOA4

      views
92     1771
220    4231
240     612
334     482
424   51783
508    1666
627   51458
857      33
881      31
898   45887
1191   1949

Duplicated video_id rows: 0
Empty DataFrame
Columns: [video_id, title, channel_name, views]
Index: []

Zero-length videos:
                                                  title        channel_name  \
40             Career Questions with Rob Fuller @mubix!        John Hammond
98         App Performance #AskAndroid | Spotlight Week  Android Developers
576   Saddle up for success: Inside the ReArchitectu...          AWS Events
577   MariaDB: Innovation & Vision with Creator Mont...          AWS Events
578   A FinOps guide to re:Invent 2025 | The Keys to...          AWS Events
1020  anywidget: Jupyter Widgets made easy - Talk Py...         Talk Python

     duration  views
40        P0D      0
98        P0D      0
576       P0D      0
577       P0D      0
578       P0D      0
1020      P0D      0